apiVersion: v1
kind: Service
metadata:
  name: abc-site-service
spec:
  type: NodePort
  selector:
    app: abc-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
